name: regular_integration_tests
publish_to: none

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=2.2.0"

dependencies:
  flutter:
    sdk: flutter
  url_launcher:
    path: ../../url_launcher/
dependency_overrides:
  url_launcher_web:
    path: ../
  url_launcher_platform_interface:
    path: ../../url_launcher_platform_interface/

dev_dependencies:
  build_runner: ^2.1.1
  flutter_driver:
    sdk: flutter
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter
  mockito: ^5.0.0
